version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - mvn package -DskipTests
    post_build:
      commands:
        - echo $(basename ./target/*.jar)
cache:
  paths:
    - '/root/.m2/**/*'