version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - mvn package -DskipTests
    post_build:
      commands:
        - echo $(basename ./target/*.jar)

artifacts:
  files:
    - appspec.yml
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'